- name: Download and Merge JSON Files
  run: |
    python <<EOF
    import requests
    import pandas as pd

    urls = [
        "https://sql.telemetry.mozilla.org/api/queries/101785/results.json?api_key=5ynVkkPtGWDrzRkaj02GkFifGILHtqoqkngK6Nkw",
        "https://sql.telemetry.mozilla.org/api/queries/101807/results.json?api_key=mq9Z2VNBaphOVvt94YtUJVBGxxA6NpPrnG7dtHrq",
        "https://sql.telemetry.mozilla.org/api/queries/101771/results.json?api_key=a852JNzIiOv9Wu53e9m4FYDplIfYnNOc0cFJfDa3"
    ]

    all_data = []
    for url in urls:
        response = requests.get(url)
        data = response.json()
        rows = data.get("query_result", {}).get("data", {}).get("rows", [])
        all_data.extend(rows)

    try:
        with open('js-metrics-data.json', 'r') as file:
            existing_data = pd.read_json(file, lines=True)
            all_data.extend(existing_data.to_dict(orient='records'))
    except FileNotFoundError:
        print("js-metrics-data.json not found, starting with downloaded data.")

    df = pd.DataFrame(all_data)
    df = df.drop_duplicates(subset=['date', 'channel', 'os', 'metric'], keep='last')
    df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')
    df = df.sort_values(by='date')
    df.to_json('js-metrics-data.json', orient='records', lines=True)
    EOF
